# Generated by Django 2.1.1 on 2019-12-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.TextField()),
                ('status', models.TextField()),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_employee.Employee')),
            ],
        ),
    ]
